Feat/list filter
benthieu/gehWeg pull request #21
Opened 2023-09-21 19:53 UTC by wolfvlkl

2023-09-21 22:09 UTC, MarcRaemy approved these changes
Weiss nicht, wie preview testen, aber code sieht gut aus.

2023-09-25 07:23 UTC, benthieu commented on src/app/state/state.context.tsx
> +      .from( 'offer_json' )
Dies könnte man so umbauen, um zu verhindern, das Query unnötig aufzubauen, wenn kein Filter gesetzt ist:
```
const query = supabaseClient
      .from('offer_json')
      .select('*')
      .order('created_at', { ascending: false });
    if (filter.category) {
      query.like('category', filter.category);
    }
    if (filter.title) {
      query.ilike('subject', filter.title);
    }
```
Zusätzlich bitte `.eq( 'status', 'new' )` entfernen, da wir hier noch eine Story offen haben, wie wir abgelaufene Angebote handeln

2023-09-25 07:24 UTC, benthieu requested changes
Siehe Comment

2023-09-26 15:28 UTC, benthieu commented
Es braucht noch eine Kategorie "Alle" um den Filter zu clearen

2023-09-26 15:36 UTC, benthieu commented
MenuList muss raus.
1. Irgendwie gibts da ein Keylistener auf 'K'
2. Sieht auch besser aus ohne 👍🏻

2023-09-26 15:38 UTC, benthieu commented on src/app/offer-list-filter/list-filter.tsx
> +        <MenuItem >
```
  return (
    <>
      <FilterTitle title={''} updateTitle={updateTitle} />
      <FilterCategory
        categories={selectCategories}
        updateCategory={updateCategory}
      />
    </>
  );
```

Irgendwie so

2023-09-26 15:39 UTC, benthieu commented on src/app/offer-list-filter/filter-category.tsx
> +        <TextField
Hier sollte statt ein `TextField` ein `Select` sein oder?
Anhand von: https://mui.com/material-ui/react-select/

2023-09-26 16:26 UTC, wolfvlkl commented on src/app/offer-list-filter/list-filter.tsx
> +        <MenuItem >
- [refactoring ]

2023-09-26 16:28 UTC, wolfvlkl commented on src/app/offer-list-filter/list-filter.tsx
> +        <MenuItem >
- [ ] refactor

2023-09-26 16:30 UTC, wolfvlkl commented
> Es braucht noch eine Kategorie "Alle" um den Filter zu clearen

- [x] add "Alle" option

2023-09-26 16:31 UTC, wolfvlkl commented on src/app/offer-list-filter/filter-category.tsx
> +        <TextField
geht auch mit TextField

2023-09-26 16:32 UTC, wolfvlkl commented on src/app/state/state.context.tsx
> +      .from( 'offer_json' )
- [x] refactor selection

2023-09-26 16:46 UTC, wolfvlkl commented
> MenuList muss raus.
> 
> 1. Irgendwie gibts da ein Keylistener auf 'K'
> 2. Sieht auch besser aus ohne 👍🏻

Der Keylistener auf "K" ist interessanterweise im deploy-preview nicht mehr präsent.

2023-09-26 17:12 UTC, wolfvlkl commented on src/app/offer-list-filter/filter-category.tsx
> +        <TextField
- [ ] change rendering type

2023-09-28 06:39 UTC, benthieu approved these changes

2023-09-28 06:44 UTC, wolfvlkl commented
filter list by criteria

2023-09-28 06:45 UTC, merged